#Authors: Deus & Dan
#Date: 01/03/2023
#Title: Rebound to normal RSV dynamics post COVID-19 suppression

#====================================================================
# WORLD HEALTH ORGANISATION DATA (VIA FLUNET)
#====================================================================

#read the WHO RSV update file into R
#source (https://www.who.int/teams/global-influenza-programme/surveillance-and-monitoring/influenza-surveillance-outputs)
rsv <- runIfExpired('who_rsv', maxage = 168, ~read.csv(curl("https://frontdoor-l4uikgap6gz3m.azurefd.net/FLUMART/VIW_FNT?$format=csv")))

#set strings as factors to false globally
base::options(stringsAsFactors = FALSE)

#get the required variables
rsvds <-
  rsv %>%
  dplyr::filter(!is.na(RSV)) %>%
  dplyr::select(HEMISPHERE, WHOREGION, COUNTRY_AREA_TERRITORY, MMWR_WEEKSTARTDATE, ORIGIN_SOURCE, RSV) %>%
  dplyr::rename("hemi" = HEMISPHERE,
                "region" = WHOREGION,
                "country" = COUNTRY_AREA_TERRITORY,
                "date"= MMWR_WEEKSTARTDATE,
                "sentin" = ORIGIN_SOURCE,
                "cases" = RSV)

#view structure of data
utils::str(rsvds)

#expand the dataset to have single case per row
rsvds <- 
  rsvds %>% 
  dplyr::arrange(hemi, region, country, date, sentin) %>%
  utils::type.convert(as.is = TRUE) %>% 
  tidyr::uncount(cases)

#view structure of data
utils::str(rsvds)

#assign data types to variables
rsvds <-
  rsvds %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                date = lubridate::ymd(date),
                sentin = factor(sentin))

# view structure of data
utils::str(rsvds)

#====================================================================

#filter to only have these countries included from Africa with somewhat case complete data from 2017
rsv_afr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Central African Republic", "Côte d'Ivoire", "Madagascar", "South Africa"), year(date) >= 2017) %>%
  dplyr::mutate(country = if_else(country == "Côte d'Ivoire", "Ivory Coast", country))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_afr <- 
  rsv_afr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(hemi, region, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_afr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_afr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_afr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_afr <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases), 
                              temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_afr %>% 
  janitor::get_dupes(country, date)

rsv_afr <- 
  rsv_afr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from South East Asia with somewhat case complete data from 2017
rsv_sear <- 
  rsvds %>%
  dplyr::filter(country %in% c("India"), year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_sear <- 
  rsv_sear %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_sear %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_sear %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_sear %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_sear <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases), 
                               temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_sear %>% 
  janitor::get_dupes(country, date)

rsv_sear <- 
  rsv_sear %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Western Pacific with somewhat case complete data from 2017
rsv_wpr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Australia", "Japan", "Mongolia", "Malaysia"), year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_wpr <- 
  rsv_wpr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_wpr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_wpr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_wpr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_wpr <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases),
                              temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_wpr %>% 
  janitor::get_dupes(country, date)

rsv_wpr <- 
  rsv_wpr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Eastern Mediterranean with somewhat case complete data from 2017
rsv_emr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Oman", "Qatar"), year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_emr <- 
  rsv_emr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_emr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_emr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_emr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_emr <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases), 
                       temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_emr %>% 
  janitor::get_dupes(country, date)

rsv_emr <- 
  rsv_emr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)


#====================================================================

#filter to only have these countries included from Europe with somewhat case complete data from 2017
rsv_euro <- 
  rsvds %>%
  dplyr::filter(country %in% c("France", "Germany", "Netherlands", "Netherlands (Kingdom of the)", "Spain", "Portugal", "Iceland",
                               "Ireland", "Denmark", "Sweden", "United Kingdom, England", 
                               "United Kingdom, Northern Ireland", "United Kingdom, Scotland",
                               "Bulgaria", "Hungary", "Slovakia"), year(date) >= 2017) %>%
  dplyr::mutate(country = if_else(country == "United Kingdom, Northern Ireland", "Northern Ireland",
                                  if_else(country == "United Kingdom, Scotland", "Scotland",
                                          if_else(country == "United Kingdom, England", "England",
                                                  if_else(country == "Netherlands (Kingdom of the)", "Netherlands", country)))))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_euro <- 
  rsv_euro %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_euro %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_euro %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_euro %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases, na.rm = TRUE)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_euro <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases), 
                               temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_euro %>% 
  janitor::get_dupes(country, date)

rsv_euro <- 
  rsv_euro %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Americas with somewhat case complete data from 2017
rsv_amer <- 
  rsvds %>%
  dplyr::filter(country %in% c("Argentina", "Belize", "Bolivia (Plurinational State of)", "Brazil", "Canada", "Colombia", "Costa Rica",
                               "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Honduras", "Mexico",
                               "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay"), year(date) >= 2017) %>%
  dplyr:: mutate(country = if_else(country == "Bolivia (Plurinational State of)", "Bolivia",
                                   if_else(country == "Dominican Republic", "Dominica", country)))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_amer <- 
  rsv_amer %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_amer %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_amer %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_amer %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                                 if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                         if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_amer <- dplyr::rows_append(temp_ms %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases), 
                               temp_st %>% dplyr::select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_amer %>% 
  janitor::get_dupes(country, date)

rsv_amer <- 
  rsv_amer %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#combine all the global datasets
rsv_who <- 
  rsv_afr %>% 
  dplyr::bind_rows(rsv_sear) %>%
  dplyr::bind_rows(rsv_wpr) %>%
  dplyr::bind_rows(rsv_emr) %>%
  dplyr::bind_rows(rsv_euro) %>%
  dplyr::bind_rows(rsv_amer) %>%
  mutate(region = if_else(region == "AFR", "Africa",
                          if_else(region == "AMR", "Americas",
                                  if_else(region == "EMR", "Eastern Mediterranean",
                                          if_else(region == "EUR", "Europe",
                                                  if_else(region == "SEAR", "South East Asia", "Western Pacific"))))),
         hemi = if_else(hemi == "SH", "Southern hemisphere", "Northern hemisphere"))

#====================================================================
# UNITED STATES DATA
#====================================================================

#read the CDC RSV update file/dataset into R, both case detection and testing (US regional data from 2021 onwards)
#source (https://www.cdc.gov/surveillance/nrevss/rsv/region.html)
rsv_usaNE <- runIfExpired('usa_rsv/rsv2021NE+', maxage = 168, ~XML::readHTMLTable(getURL("https://www.cdc.gov/surveillance/nrevss/images/trend_images/RSV14NumCent5AVG_Reg1.htm",.opts = list(ssl.verifypeer = FALSE)), header = TRUE))[["RSV Numerator Data for Census Region 1(5 week Average)"]]
rsv_usaMW <- runIfExpired('usa_rsv/rsv2021MW+', maxage = 168, ~XML::readHTMLTable(getURL("https://www.cdc.gov/surveillance/nrevss/images/trend_images/RSV14NumCent5AVG_Reg2.htm",.opts = list(ssl.verifypeer = FALSE)), header = TRUE))[["RSV Numerator Data for Census Region 2(5 week Average)"]]
rsv_usaSo <- runIfExpired('usa_rsv/rsv2021So+', maxage = 168, ~XML::readHTMLTable(getURL("https://www.cdc.gov/surveillance/nrevss/images/trend_images/RSV14NumCent5AVG_Reg3.htm",.opts = list(ssl.verifypeer = FALSE)), header = TRUE))[["RSV Numerator Data for Census Region 3(5 week Average)"]]
rsv_usaWe <- runIfExpired('usa_rsv/rsv2021We+', maxage = 168, ~XML::readHTMLTable(getURL("https://www.cdc.gov/surveillance/nrevss/images/trend_images/RSV14NumCent5AVG_Reg4.htm",.opts = list(ssl.verifypeer = FALSE)), header = TRUE))[["RSV Numerator Data for Census Region 4(5 week Average)"]]
rsv_usaFl <- runIfExpired('usa_rsv/rsv2021Fl+', maxage = 168, ~XML::readHTMLTable(getURL("https://www.cdc.gov/surveillance/nrevss/images/trend_images/RSV14NumCent5AVG_FL.htm",.opts = list(ssl.verifypeer = FALSE)), header = TRUE))[["RSV Data for Florida(5 week Average)"]]

#data wrangling
rsv_usa_reg1 <-
  base::rbind(
    
    rsv_usaNE %>% 
      dplyr::select(RepWeekDate, `PCR Detections`) %>% #we are reading Antigen test results only but its incorrectly labeled as PCR from source data
      dplyr::rename("date" = "RepWeekDate", cases = `PCR Detections`) %>%
      dplyr::mutate(regionUS = "United States North East"),
    
    rsv_usaMW %>% 
      dplyr::select(RepWeekDate, `PCR Detections`) %>% #we are reading Antigen test results only but its incorrectly labeled as PCR from source data
      dplyr::rename("date" = "RepWeekDate", cases = `PCR Detections`) %>%
      dplyr::mutate(regionUS = "United States Mid West"),
    
    rsv_usaSo %>% 
      dplyr::select(RepWeekDate, `PCR Detections`) %>% #we are reading Antigen test results only but its incorrectly labeled as PCR from source data
      dplyr::rename("date" = "RepWeekDate", cases = `PCR Detections`) %>%
      dplyr::mutate(regionUS = "United States South"),
    
    rsv_usaWe %>% 
      dplyr::select(RepWeekDate, `PCR Detections`) %>% #we are reading Antigen test results only but its incorrectly labeled as PCR from source data
      dplyr::rename("date" = "RepWeekDate", cases = `PCR Detections`) %>%
      dplyr::mutate(regionUS = "United States West"),
    
    rsv_usaFl %>% 
      dplyr::select(RepWeekDate, `PCR Detections`) %>% #we are reading Antigen test results only but its incorrectly labeled as PCR from source data
      dplyr::rename("date" = "RepWeekDate", cases = `PCR Detections`) %>%
      dplyr::mutate(regionUS = "United States South")) %>%
  
  dplyr::mutate(cases = as.integer(cases),
                date = lubridate::mdy(date),
                hemi = "Northern hemisphere",
                region = "Americas",
                country = "United States") %>%
  dplyr::select(hemi, region, country, regionUS, date, cases)

#view structure of data
utils::str(rsv_usa_reg1)

#expand the dataset to have single case per row
rsv_usa_reg1 <- 
  rsv_usa_reg1 %>% 
  utils::type.convert(as.is = TRUE) %>% 
  tidyr::uncount(cases)

#view structure of data
utils::str(rsv_usa_reg1)

#assign data types to variables
rsv_usa_reg1 <-
  rsv_usa_reg1 %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                regionUS = regionUS,
                date = lubridate::ymd(date))

# view structure of data
utils::str(rsv_usa_reg1)

#====================================================================

#read the CDC RSV update file/dataset into R (US regional data from 2020 backwards)
#source (https://healthdata.gov/dataset/Respiratory-Syncytial-Virus-Laboratory-Data-NREVSS/7zgq-bp9w)
rsv_usa_reg2 <- runIfExpired('usa_rsv/rsv2020-', maxage = 168, ~read.csv(curl("https://data.cdc.gov/api/views/52kb-ccu2/rows.csv?accessType=DOWNLOAD")))

#get the required variables
rsv_usa_reg2 <-
  rsv_usa_reg2 %>%
  dplyr::filter(!is.na(RSV.Detections)) %>%
  dplyr::select(Week.ending.Date, HHS.region, RSV.Detections) %>%
  dplyr::mutate(hemi = "Northern hemisphere",
                region = "Americas",
                country = "United States",
                Week.ending.Date = lubridate::dmy(Week.ending.Date),
                regionUS = if_else(HHS.region == 1 | HHS.region == 2, "United States North East", #collapse HHS regions into census regions (as only census regional data are scrappable post 2020)
                                   if_else(HHS.region == 3 | HHS.region == 4 | HHS.region == 6, "United States South",
                                           if_else(HHS.region == 5 | HHS.region == 7, "United States Mid West", "United States West")))) %>%
  dplyr::rename("date"= Week.ending.Date,
                "cases" = RSV.Detections) %>%
  dplyr::select(hemi, region, country, regionUS, date, cases)

#view structure of data
utils::str(rsv_usa_reg2)

#expand the dataset to have single case per row
rsv_usa_reg2 <- 
  rsv_usa_reg2 %>% 
  utils::type.convert(as.is = TRUE) %>% 
  tidyr:: uncount(cases)

#view structure of data
utils::str(rsv_usa_reg2)

#assign data types to variables
rsv_usa_reg2 <-
  rsv_usa_reg2 %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                regionUS = regionUS,
                date = lubridate::ymd(date))

# view structure of data
utils::str(rsv_usa_reg2)

#====================================================================

#combine dataset from 2020 backwards (rsv_usa2) and 2021 onwards (rsv_usa1)
rsv_usa_reg <-
  dplyr::rows_append(
    rsv_usa_reg1,
    rsv_usa_reg2)
base::rm(rsv_usa_reg1, rsv_usa_reg2)

#properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_usa_reg <- 
  rsv_usa_reg %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, regionUS, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, regionUS, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country, regionUS), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, regionUS, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#check for duplicates by country and date
rsv_usa_reg %>% 
  janitor::get_dupes(regionUS, date)

rsv_usa_reg <- 
  rsv_usa_reg %>% 
  dplyr::filter(yr >= 2017) %>%
  dplyr::distinct(regionUS, date, .keep_all = TRUE) %>%
  dplyr::select(hemi, region, country, date, cases, yr, mo, wk, regionUS)

#====================================================================

#combine regional datasets to make national then combine with each region in single dataset
rsv_usa <-
  rsv_usa_reg %>% 
  dplyr::select(everything(), -regionUS) %>% 
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>% 
  dplyr::summarise(cases = sum(cases, na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(regionUS = "United States") %>%
  dplyr::select(hemi:date,  yr, mo, wk, regionUS, cases) %>%
  dplyr::rows_append(rsv_usa_reg)

#====================================================================
#====================================================================

#combine USA data and global data
rsv_all <-
  dplyr::bind_rows(
    rsv_usa %>% 
      dplyr::mutate(country = regionUS) %>%
      dplyr::select(hemi:date, yr:wk, cases),
    rsv_who
  )

#separate north and south Americas
rsv_all <- 
  rsv_all %>%
  dplyr::mutate(region = if_else(country %in% c("Argentina", "Belize", "Bolivia", "Brazil", "Colombia", "Costa Rica", "Dominica", "Ecuador", "El Salvador", 
                                         "Guatemala", "Honduras", "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay"), "South Americas",
                          if_else(country %in% c("Canada", "Mexico", "United States", "United States Mid West", "United States North East", 
                                                 "United States South", "United States West"), "North Americas", region)))

#delete all temporary datasets
rm(list = grep("rsv_all", ls(), value = TRUE, invert = TRUE))

#====================================================================
#CLIMATE RELATED DATA
#====================================================================

#import climate data that assign each country to temperate or tropical for easy weekly scaling
climate <-
  rio::import(here::here("data", "climate", "climate.csv"))

#================================================================
# DOWNLOAD AND BUILD A STRINGENCY DATASET
#================================================================

#input dynamics stringency dataset
stringency <- read.csv(curl("https://covid.ourworldindata.org/data/owid-covid-data.csv"))

stringency <-
  stringency %>%
  dplyr::select(location, date, stringency_index, population_density, median_age) %>%
  dplyr::rename("country" = location, "fdate" = date, "strin_indx" = stringency_index, "pop_dens" = population_density, "med_age" = median_age) %>%
  dplyr::filter(!is.na(strin_indx)) %>%
  dplyr::mutate(fdate = date(fdate),
                country = ifelse(country == "United Kingdom", "Scotland", country))

stringency <-
  stringency %>%
  dplyr::filter(country == "Scotland") %>%
  dplyr::mutate(country = ifelse(country == "Scotland", "Northern Ireland", country)) %>%
  dplyr::bind_rows(stringency)

#====================================================================
#SET PROPER DATA BOUNDARIES FOR ANALYSIS
#====================================================================

#set southern hemisphere countries to start from 1st week of 2017 to 52th week of 2022
rsv_allSo <-
rsv_all %>%
  dplyr::filter(country %in% c("Argentina", "Australia", "Colombia", "Costa Rica", "India", "Japan", "Paraguay", "Peru", "South Africa") &
                  date >= date("2017-01-08") &
                  date <= date("2022-12-31")
                )

#set northern hemisphere countries to start from 24th week of 2017 to 23rd week of 2023
rsv_allNo <-
  rsv_all %>%
  dplyr::filter(country %in% c("Brazil", "Canada", "Denmark", "France", "Germany", "Hungary", "Iceland", "Ireland", "Mexico", "Mongolia", "Netherlands", "Northern Ireland", "Oman", "Portugal", "Qatar", "Scotland", "Spain", "Sweden", "United States") &
                  date >= date("2017-06-11") &
                  date < date("2023-06-04")
  )

#now combine the datasets
rsv_all <-
bind_rows(rsv_allSo, rsv_allNo)

# rsv_all <-
#   rsv_all %>%
#   dplyr::filter(date <= date("2023-02-28"))
